"""Fictional operating worlds used by the Symbiosis beta.

All organisations, people, assets, events, policies, and outcomes in this
module are synthetic. The application combines these with live device time and
time-zone logic to create a coherent operating simulation.
"""

from __future__ import annotations

from typing import Any


REGIONS: list[dict[str, str]] = [
    {"city": "New York", "zone": "America/New_York", "code": "NYC", "x": "18", "y": "58"},
    {"city": "London", "zone": "Europe/London", "code": "LDN", "x": "43", "y": "38"},
    {"city": "Singapore", "zone": "Asia/Singapore", "code": "SGP", "x": "72", "y": "66"},
    {"city": "Tokyo", "zone": "Asia/Tokyo", "code": "TYO", "x": "82", "y": "42"},
    {"city": "Sydney", "zone": "Australia/Sydney", "code": "SYD", "x": "88", "y": "79"},
]


WORLD_PROFILES: dict[str, dict[str, Any]] = {
    "axiom": {
        "id": "axiom",
        "name": "Axiom Digital Markets",
        "short_name": "AXIOM",
        "subtitle": "24/7 institutional digital-asset network",
        "domain": "Institutional digital assets",
        "accent": "#5c8dff",
        "accent_soft": "#8daeff",
        "metric_label": "Value protected",
        "metric_value": "$1.84M",
        "open_cases": 14,
        "review_cases": 3,
        "current_user": {
            "name": "Maya Chen",
            "role": "Regional Risk Lead",
            "city": "Singapore",
            "zone": "Asia/Singapore",
            "initials": "MC",
        },
        "templates": [
            {
                "id": "axm-settlement",
                "type": "Settlement exception",
                "title": "Institutional conversion request",
                "origin": "Axiom Custody · Singapore",
                "destination": "Northshore Settlement Bank · New York",
                "value": "$2.84M",
                "notional": "842 ORBIT equivalent → USD settlement",
                "window": "01:42 settlement window remaining",
                "risk": "Moderate",
                "confidence": 78,
                "recommendation": "Authorize with conditions",
                "recommendation_key": "condition",
                "signal": "Beneficiary relationship requires a refreshed ownership confirmation.",
                "evidence": [
                    {"state": "verified", "source": "Custody continuity", "claim": "Established institutional relationship across 19 prior settlements.", "recency": "Live", "reliability": "High", "impact": "Supports authorization"},
                    {"state": "verified", "source": "Liquidity engine", "claim": "USD route can satisfy the settlement window without concentration pressure.", "recency": "18s", "reliability": "High", "impact": "Protects value"},
                    {"state": "conflicting", "source": "Counterparty graph", "claim": "Declared beneficiary differs from the latest relationship signal.", "recency": "4m", "reliability": "Medium", "impact": "Raises exposure"},
                    {"state": "missing", "source": "Beneficial ownership", "claim": "Latest verified ownership document is awaiting refresh.", "recency": "26h", "reliability": "Pending", "impact": "Decision-changing"},
                ],
                "options": [
                    {"key": "authorize", "label": "Authorize now", "summary": "Fastest settlement and client continuity.", "protect": "$2.84M settlement window", "expose": "Elevated relationship exposure", "friction": "None", "confidence": 59, "tone": "risk"},
                    {"key": "condition", "label": "With conditions", "summary": "Preserves value while adding a verified control.", "protect": "$2.61M expected value", "expose": "Limited verification delay", "friction": "90 seconds", "confidence": 78, "tone": "recommended", "conditions": ["Refresh beneficial ownership", "Enhanced route monitoring", "Authorization expires in 24 hours"]},
                    {"key": "hold", "label": "Hold / escalate", "summary": "Maximum control while the relationship signal is resolved.", "protect": "Highest compliance buffer", "expose": "$430K opportunity cost", "friction": "Missed window likely", "confidence": 91, "tone": "neutral"},
                ],
                "challenge": "A failed ownership refresh, a new high-risk wallet relationship, or a material route change moves this decision to Hold.",
            },
            {
                "id": "axm-liquidity",
                "type": "Liquidity routing",
                "title": "Liquidity corridor imbalance",
                "origin": "Axiom Treasury · London",
                "destination": "APAC custody corridor · Singapore",
                "value": "$1.16M",
                "notional": "ORBIT / USD corridor rebalance",
                "window": "04:08 execution window remaining",
                "risk": "Elevated",
                "confidence": 71,
                "recommendation": "Authorize with conditions",
                "recommendation_key": "condition",
                "signal": "The most efficient route crosses a temporarily elevated counterparty concentration threshold.",
                "evidence": [
                    {"state": "verified", "source": "Treasury position", "claim": "London reserve is above the policy floor after the proposed route.", "recency": "Live", "reliability": "High", "impact": "Supports route"},
                    {"state": "verified", "source": "Execution simulator", "claim": "Route B reduces expected slippage by 31 basis points.", "recency": "11s", "reliability": "High", "impact": "Unlocks value"},
                    {"state": "conflicting", "source": "Counterparty concentration", "claim": "Route B exceeds the preferred concentration target by 6%.", "recency": "Live", "reliability": "High", "impact": "Raises exposure"},
                    {"state": "missing", "source": "APAC operations", "claim": "Local settlement capacity confirmation is still pending.", "recency": "2m", "reliability": "Pending", "impact": "Decision-changing"},
                ],
                "options": [
                    {"key": "authorize", "label": "Authorize route B", "summary": "Lowest expected cost with a temporary concentration exception.", "protect": "$184K execution value", "expose": "Concentration threshold breach", "friction": "None", "confidence": 62, "tone": "risk"},
                    {"key": "condition", "label": "With conditions", "summary": "Use route B with a capped exposure and APAC acknowledgement.", "protect": "$146K expected value", "expose": "Controlled concentration", "friction": "2 minute check", "confidence": 71, "tone": "recommended", "conditions": ["Cap route allocation at 64%", "Require APAC settlement acknowledgement", "Monitor counterparty exposure"]},
                    {"key": "hold", "label": "Hold / escalate", "summary": "Wait for a lower-concentration route or executive exception.", "protect": "Policy adherence", "expose": "$210K slippage exposure", "friction": "Window deterioration", "confidence": 87, "tone": "neutral"},
                ],
                "challenge": "If APAC capacity falls below the reserve threshold or counterparty exposure rises another 4%, route B is no longer defensible.",
            },
            {
                "id": "axm-wallet",
                "type": "Counterparty review",
                "title": "Institutional wallet relationship update",
                "origin": "Client operations · Tokyo",
                "destination": "Axiom compliance review · London",
                "value": "$740K",
                "notional": "New institutional settlement relationship",
                "window": "Policy review due in 05:20",
                "risk": "Moderate",
                "confidence": 82,
                "recommendation": "Authorize with conditions",
                "recommendation_key": "condition",
                "signal": "The relationship is established, but one indirect exposure signal needs ongoing monitoring.",
                "evidence": [
                    {"state": "verified", "source": "Institutional identity", "claim": "Legal entity, mandate, and signatory chain match approved records.", "recency": "Live", "reliability": "High", "impact": "Supports authorization"},
                    {"state": "verified", "source": "Behavioral continuity", "claim": "Settlement pattern aligns with the client’s approved operating profile.", "recency": "9m", "reliability": "High", "impact": "Supports authorization"},
                    {"state": "conflicting", "source": "Relationship network", "claim": "One indirect exposure signal remains outside the preferred risk band.", "recency": "7m", "reliability": "Medium", "impact": "Raises exposure"},
                    {"state": "missing", "source": "Enhanced review", "claim": "Secondary jurisdiction attestation has not yet been supplied.", "recency": "Pending", "reliability": "Pending", "impact": "Decision-changing"},
                ],
                "options": [
                    {"key": "authorize", "label": "Authorize now", "summary": "Enable the relationship under the current operating mandate.", "protect": "$740K opportunity", "expose": "Open indirect exposure", "friction": "None", "confidence": 67, "tone": "risk"},
                    {"key": "condition", "label": "With conditions", "summary": "Enable with a temporary limit and a required attestation.", "protect": "$684K expected value", "expose": "Bounded exposure", "friction": "One follow-up", "confidence": 82, "tone": "recommended", "conditions": ["Set temporary relationship limit", "Collect jurisdiction attestation", "Review indirect exposure in 7 days"]},
                    {"key": "hold", "label": "Hold / escalate", "summary": "Wait for a completed enhanced review.", "protect": "Maximum assurance", "expose": "Delayed client activation", "friction": "5–7 business days", "confidence": 93, "tone": "neutral"},
                ],
                "challenge": "A failed jurisdiction attestation or a widening indirect exposure relationship changes this decision to Hold.",
            },
        ],
    },
    "northstar": {
        "id": "northstar",
        "name": "Northstar Financial Group",
        "short_name": "NORTHSTAR",
        "subtitle": "Global banking and payment operations",
        "domain": "Global payments",
        "accent": "#33c7a5",
        "accent_soft": "#7ee8d1",
        "metric_label": "Exposure avoided",
        "metric_value": "$920K",
        "open_cases": 9,
        "review_cases": 2,
        "current_user": {
            "name": "Daniel Okafor",
            "role": "Compliance Lead",
            "city": "London",
            "zone": "Europe/London",
            "initials": "DO",
        },
        "templates": [
            {
                "id": "nsg-settlement",
                "type": "Cross-border settlement",
                "title": "Payment corridor exception",
                "origin": "Northstar Treasury · London",
                "destination": "Pacific settlement partner · Singapore",
                "value": "$4.12M",
                "notional": "Corporate settlement instruction",
                "window": "00:56 settlement window remaining",
                "risk": "Moderate",
                "confidence": 80,
                "recommendation": "Authorize with conditions",
                "recommendation_key": "condition",
                "signal": "A time-sensitive settlement can proceed if a conflicting beneficiary signal is contained.",
                "evidence": [
                    {"state": "verified", "source": "Client mandate", "claim": "Instruction is within the approved corporate payment mandate.", "recency": "Live", "reliability": "High", "impact": "Supports authorization"},
                    {"state": "verified", "source": "Liquidity desk", "claim": "Preferred corridor remains available within the service-level target.", "recency": "13s", "reliability": "High", "impact": "Protects value"},
                    {"state": "conflicting", "source": "Beneficiary assurance", "claim": "Beneficiary address was updated after the last verified instruction.", "recency": "3m", "reliability": "Medium", "impact": "Raises exposure"},
                    {"state": "missing", "source": "Relationship manager", "claim": "Out-of-band confirmation has not yet been attached.", "recency": "Pending", "reliability": "Pending", "impact": "Decision-changing"},
                ],
                "options": [
                    {"key": "authorize", "label": "Authorize now", "summary": "Release through the preferred corridor before cutoff.", "protect": "$4.12M settlement", "expose": "Beneficiary-change exposure", "friction": "None", "confidence": 63, "tone": "risk"},
                    {"key": "condition", "label": "With conditions", "summary": "Release with beneficiary containment and confirmation follow-up.", "protect": "$3.98M expected value", "expose": "Bounded exposure", "friction": "45 second delay", "confidence": 80, "tone": "recommended", "conditions": ["Tag beneficiary update", "Require out-of-band confirmation", "Route through enhanced monitoring"]},
                    {"key": "hold", "label": "Hold / escalate", "summary": "Wait for relationship-manager confirmation.", "protect": "Maximum control", "expose": "$620K client-impact exposure", "friction": "Cutoff likely missed", "confidence": 94, "tone": "neutral"},
                ],
                "challenge": "A failed confirmation or any change to the originating mandate makes an immediate hold mandatory.",
            },
            {
                "id": "nsg-counterparty",
                "type": "Counterparty exception",
                "title": "Correspondent bank exposure review",
                "origin": "Northstar Risk · New York",
                "destination": "European settlement corridor · London",
                "value": "$3.36M",
                "notional": "Temporary counterparty limit extension",
                "window": "Limit expires in 03:18",
                "risk": "Elevated",
                "confidence": 74,
                "recommendation": "Authorize with conditions",
                "recommendation_key": "condition",
                "signal": "The extension is economically useful but needs a documented limit and rapid refresh.",
                "evidence": [
                    {"state": "verified", "source": "Exposure ledger", "claim": "Current exposure remains inside hard policy limits.", "recency": "Live", "reliability": "High", "impact": "Supports extension"},
                    {"state": "verified", "source": "Operations", "claim": "The extension prevents two downstream settlement breaks.", "recency": "5m", "reliability": "High", "impact": "Unlocks value"},
                    {"state": "conflicting", "source": "External risk signal", "claim": "Recent rating movement challenges the preferred soft limit.", "recency": "11m", "reliability": "Medium", "impact": "Raises exposure"},
                    {"state": "missing", "source": "Counterparty desk", "claim": "Updated intraday collateral position is pending.", "recency": "Pending", "reliability": "Pending", "impact": "Decision-changing"},
                ],
                "options": [
                    {"key": "authorize", "label": "Authorize extension", "summary": "Keep the corridor fully available through the settlement peak.", "protect": "$3.36M corridor value", "expose": "Soft-limit breach", "friction": "None", "confidence": 58, "tone": "risk"},
                    {"key": "condition", "label": "With conditions", "summary": "Grant a capped extension pending collateral refresh.", "protect": "$2.94M expected value", "expose": "Capped exposure", "friction": "15 minute review", "confidence": 74, "tone": "recommended", "conditions": ["Cap extension at 72%", "Require intraday collateral refresh", "Reassess at 15 minutes"]},
                    {"key": "hold", "label": "Hold / escalate", "summary": "Escalate to the counterparty risk chair.", "protect": "Policy certainty", "expose": "Downstream break risk", "friction": "Manual contingency", "confidence": 89, "tone": "neutral"},
                ],
                "challenge": "A collateral shortfall or further rating deterioration removes the conditions under which the extension is acceptable.",
            },
        ],
    },
    "asterion": {
        "id": "asterion",
        "name": "Asterion Capital",
        "short_name": "ASTERION",
        "subtitle": "Multi-strategy investment operations and counterparty risk",
        "domain": "Investment operations",
        "accent": "#b58cff",
        "accent_soft": "#d1b7ff",
        "metric_label": "Capital safeguarded",
        "metric_value": "$6.28M",
        "open_cases": 7,
        "review_cases": 2,
        "current_user": {
            "name": "Elena Rossi",
            "role": "Executive Authorizer",
            "city": "New York",
            "zone": "America/New_York",
            "initials": "ER",
        },
        "templates": [
            {
                "id": "ast-counterparty",
                "type": "Counterparty concentration",
                "title": "Prime counterparty concentration review",
                "origin": "Asterion Portfolio Operations · New York",
                "destination": "Global Risk Committee · London",
                "value": "$8.70M",
                "notional": "Temporary margin and exposure allocation",
                "window": "Decision window closes in 02:15",
                "risk": "Elevated",
                "confidence": 76,
                "recommendation": "Authorize with conditions",
                "recommendation_key": "condition",
                "signal": "The allocation protects a time-sensitive opportunity, but temporary concentration needs a hard exit condition.",
                "evidence": [
                    {"state": "verified", "source": "Portfolio exposure", "claim": "The proposed allocation remains below hard concentration limits.", "recency": "Live", "reliability": "High", "impact": "Supports action"},
                    {"state": "verified", "source": "Liquidity model", "claim": "The allocation preserves the portfolio’s required liquidity buffer.", "recency": "17s", "reliability": "High", "impact": "Protects capital"},
                    {"state": "conflicting", "source": "Counterparty stress model", "claim": "Stress exposure rises beyond the preferred comfort band.", "recency": "Live", "reliability": "High", "impact": "Raises exposure"},
                    {"state": "missing", "source": "Prime services", "claim": "Updated intraday margin terms are awaiting confirmation.", "recency": "Pending", "reliability": "Pending", "impact": "Decision-changing"},
                ],
                "options": [
                    {"key": "authorize", "label": "Authorize allocation", "summary": "Protect the full opportunity under the current margin assumption.", "protect": "$8.70M opportunity", "expose": "Stress concentration", "friction": "None", "confidence": 61, "tone": "risk"},
                    {"key": "condition", "label": "With conditions", "summary": "Authorize a capped allocation with an automatic reassessment.", "protect": "$7.96M expected value", "expose": "Bounded stress exposure", "friction": "10 minute check", "confidence": 76, "tone": "recommended", "conditions": ["Cap allocation at 68%", "Require margin-term confirmation", "Auto-review on stress threshold"]},
                    {"key": "hold", "label": "Hold / escalate", "summary": "Wait for the risk committee to approve the exception.", "protect": "Maximum governance", "expose": "$1.24M opportunity cost", "friction": "Delayed execution", "confidence": 92, "tone": "neutral"},
                ],
                "challenge": "A margin-term change or a breach of the stress threshold means the proposed allocation should not proceed.",
            },
            {
                "id": "ast-liquidity",
                "type": "Liquidity exception",
                "title": "Portfolio liquidity contingency",
                "origin": "Asterion Risk · Tokyo",
                "destination": "Portfolio leadership · New York",
                "value": "$5.24M",
                "notional": "Temporary liquidity reserve release",
                "window": "Asia handoff in 00:38",
                "risk": "Moderate",
                "confidence": 84,
                "recommendation": "Authorize with conditions",
                "recommendation_key": "condition",
                "signal": "The release is within policy if a contingent reserve is held and the New York desk accepts the handoff.",
                "evidence": [
                    {"state": "verified", "source": "Reserve policy", "claim": "Proposed release is within the conditional reserve framework.", "recency": "Live", "reliability": "High", "impact": "Supports action"},
                    {"state": "verified", "source": "Scenario model", "claim": "Contingent reserve preserves downside coverage across modeled conditions.", "recency": "20s", "reliability": "High", "impact": "Protects capital"},
                    {"state": "conflicting", "source": "Market operations", "claim": "One venue’s expected settlement timing remains less certain.", "recency": "6m", "reliability": "Medium", "impact": "Raises exposure"},
                    {"state": "missing", "source": "New York desk", "claim": "Formal handoff acknowledgement is pending.", "recency": "Pending", "reliability": "Pending", "impact": "Decision-changing"},
                ],
                "options": [
                    {"key": "authorize", "label": "Authorize release", "summary": "Release the reserve without a contingent holdback.", "protect": "$5.24M flexibility", "expose": "Settlement timing uncertainty", "friction": "None", "confidence": 69, "tone": "risk"},
                    {"key": "condition", "label": "With conditions", "summary": "Release with a contingency reserve and desk handoff.", "protect": "$4.92M expected value", "expose": "Limited timing exposure", "friction": "Handoff required", "confidence": 84, "tone": "recommended", "conditions": ["Maintain contingency reserve", "Require New York handoff", "Reassess venue timing at open"]},
                    {"key": "hold", "label": "Hold / escalate", "summary": "Retain the full reserve until the handoff completes.", "protect": "Maximum liquidity buffer", "expose": "Lower capital efficiency", "friction": "Delayed release", "confidence": 95, "tone": "neutral"},
                ],
                "challenge": "If the contingent reserve cannot be maintained or the receiving desk rejects the handoff, retain the full reserve.",
            },
        ],
    },
}


def world_options() -> list[str]:
    """Return profile ids in their intended presentation order."""

    return ["axiom", "northstar", "asterion"]

